DROP DATABASE IF EXISTS ProjetoSite_PI2;
CREATE DATABASE ProjetoSite_PI2;

USE ProjetoSite_PI2;

CREATE TABLE IF NOT EXISTS PESSOAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SEXO VARCHAR(10) DEFAULT "ASEXO",
PASSWORD VARCHAR(50) NOT NULL
);

DESCRIBE PESSOAS;


CREATE TABLE IF NOT EXISTS PUBLICACAO(
ID INT AUTO_INCREMENT PRIMARY KEY,
IDP INT NOT NULL,
TITULO VARCHAR(50) NOT NULL,
GENERO VARCHAR(10) NOT NULL,
DESCRICAO VARCHAR(1000) NOT NULL,
IMAGEM VARCHAR(50) NOT NULL,
DATA DATETIME NOT NULL,
FOREIGN KEY (IDP) REFERENCES PESSOAS (ID)
);

DESCRIBE PUBLICACAO;